setup.py
sqlwhat/check_funcs.py
sqlwhat/check_result.py
sqlwhat/tests/test_basic.py
sqlwhat/tests/test_check_funcs.py
sqlwhat/tests/test_check_result.py
sqlwhat/tests/test_full.py
sqlwhat/tests/test_state.py
sqlwhat/tests/test_test_mc.py
travis/deploy-builds.sh

this branch is forked from check-result, so may be easier to look at that one first.

Has equal ast

---

setup.py
sqlwhat/check_funcs.py
sqlwhat/check_logic.py
sqlwhat/check_result.py
sqlwhat/tests/test_basic.py
sqlwhat/tests/test_check_funcs.py
sqlwhat/tests/test_check_logic.py
sqlwhat/tests/test_check_result.py
sqlwhat/tests/test_full.py
sqlwhat/tests/test_state.py
sqlwhat/tests/test_test_mc.py
travis/deploy-builds.sh

these pull requests will make a lot more sense if you look at the network graph first :p https://github.com/datacamp/sqlwhat/network

Test logic

---

pytest.ini
sqlwhat/check_funcs.py
sqlwhat/grammar/plsql/ast.py
sqlwhat/grammar/plsql/tests/test_examples.py
sqlwhat/tests/test_basic.py
sqlwhat/tests/test_check_funcs.py

PR is against a staging branch, feel free to merge once approved.

Test student typed

---

sqlwhat/grammar/plsql/ast.py
sqlwhat/grammar/plsql/plsql.g4
sqlwhat/grammar/plsql/tests/test_ast.py

ast shaping for SELECT statements, with some tweaks to the grammar.

Ast select fields

---

.travis.yml
setup.cfg
setup.py
sqlwhat/__init__.py

add everything for pypi, move version to init

---

sqlwhat/checks/__init__.py
sqlwhat/checks/check_funcs.py
sqlwhat/checks/check_logic.py
sqlwhat/selectors.py
sqlwhat/tests/test_basic.py
sqlwhat/tests/test_check_funcs.py
sqlwhat/tests/test_full.py
sqlwhat/tests/test_selectors.py

note that I'm merging other branches into this one, so I can use it as an ad hoc staging branch. So I would look at the other PRs first!

Rename ast checks

---

README.md
sqlwhat/Reporter.py
sqlwhat/checks/__init__.py
sqlwhat/checks/check_result.py
sqlwhat/test_exercise.py
sqlwhat/tests/test_basic.py
sqlwhat/tests/test_success_msg.py

example at https://www.datacamp.com/teach/edit/repositories/983/branches/machow-test
(exercise is named test_error)

test_error function, initialize reporter with error log

---

sqlwhat/checks/check_funcs.py

@machow can we make the default more student friendly for now? I'll need to huddle with @colinedwardricardo early next week to make sure we're not over using this, but this is probably good enough for v1

Improve default feedback for has_equal_ast

---

sqlwhat/checks/check_funcs.py
sqlwhat/tests/test_check_funcs.py

give has_equal_ast an exact option

---

sqlwhat/checks/check_funcs.py
sqlwhat/tests/test_test_mc.py

Pretty small fix, will merge and update shared image right now..

fix bug where test_mc used default success msg, add docs

---

sqlwhat/checks/check_result.py
sqlwhat/tests/test_check_result.py

fix rounding bug for columns with None

---

Makefile
README.md
docs/glossary.rst
requirements.txt
sqlwhat/checks/__init__.py
sqlwhat/checks/check_funcs.py
tests/test_full.py
tests/test_protowhat_messaging.py

@richierocks these changes would include a new function in `sqlwhat`, called `check_query()`, that allows you to run arbitrary sql statements after rerunning the student query, so you can verify whether UPDATEs, INSERTs etc happened correctly. Let me know what you think, if you have an opinion.
The docs in `sqlwhat/checks/check_funcs.py` are most interesting for you.

Fs check query

---

requirements.txt
tests/test_protowhat_check_funcs.py
tests/test_protowhat_messaging.py

Depends on antlr-tsql and antlr-plsql PR merge and release.

Update ANTLR dependencies

---

requirements.txt
setup.py
tests/test_protowhat_check_funcs.py
tests/test_protowhat_messaging.py
tests/test_selectors.py

Update sqlwhat for new AST library versions.
Relies on https://github.com/datacamp/protowhat/pull/31

Ast refactor

---

sqlwhat/State.py
tests/test_state.py

- Added a single line to the parser modules
- Added a test to get_dispatcher

[LE-856] Added support for oracle in sqlwhat

---

docs/glossary.rst
requirements.txt
sqlwhat/State.py
sqlwhat/checks/__init__.py
sqlwhat/checks/check_funcs.py

- Reuse function from protowhat
- Update dependencies

Reuse allow_errors

---

tests/test_protowhat_check_funcs.py

Add test for running has_code on a comment only

Add test for running has_code on a comment only

---

requirements.txt

Update antlr-plsql to v0.9.1

---

sqlwhat/State.py

Adds the snowflake sql dialect, uses the postgres parser (`antlr_plsql`) for now

[CP-1463] feat: add snowflake dialect

---

sqlwhat/__init__.py

[CP-1535] chore: bump version
